# Generated by Django 5.2.3 on 2025-06-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='pharmacist_banner',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacist/banner/'),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='pharmacist_bio',
            field=models.TextField(blank=True, default='pharmacist bio...', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='pharmacist_faculty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
