# Generated by Django 5.2.3 on 2025-06-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pharmacist_pharmacist_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='pharmacist_faculty_logo',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacist/faculty_logo/'),
        ),
    ]
