# Generated by Django 5.2.3 on 2025-06-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pharmacist_pharmacist_faculty_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacist',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='license_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='reject_message',
            field=models.TextField(blank=True, default='revise and send your licsense again please', null=True),
        ),
    ]
