# Generated by Django 5.2.3 on 2025-06-23 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_pharmacist_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 10, 42, 20, 86108, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
