# Generated by Django 5.2.3 on 2025-06-23 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_pharmacist_created_at_pharmacist_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='has_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 14, 59, 23, 990948, tzinfo=datetime.timezone.utc)),
        ),
    ]
