# Generated by Django 5.2.3 on 2025-06-23 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pharmacist_has_store_alter_pharmacist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 15, 8, 25, 508757, tzinfo=datetime.timezone.utc)),
        ),
    ]
