# Generated by Django 5.2.3 on 2025-06-25 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_pharmacist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 25, 17, 26, 58, 532983, tzinfo=datetime.timezone.utc)),
        ),
    ]
