# Generated by Django 5.2.3 on 2025-07-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_auth_provider_alter_pharmacist_created_at'),
        ('users', '0013_alter_pharmacist_created_at'),
    ]

    operations = [
    ]
