# Generated by Django 5.2.3 on 2025-07-01 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merge_20250701_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='medical_stores_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
