# Generated by Django 5.2.3 on 2025-07-04 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_pharmacist_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='delivery/profile/')),
                ('delivery_license', models.ImageField(upload_to='delivery/license/')),
                ('delivery_bio', models.TextField(blank=True, default='delivery bio...', max_length=255, null=True)),
                ('license_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reject_message', models.TextField(blank=True, default='revise and send your delivery license again please', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('client', 'Client'), ('pharmacist', 'Pharmacist'), ('admin', 'Admin'), ('delivery', 'Delivery')], default='guest', max_length=15),
        ),
    ]
