# Generated by Django 5.2.3 on 2025-07-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_delivery_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='default_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='default_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
