# Generated by Django 5.2.3 on 2025-06-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_type', models.CharField(choices=[('medical_devices', 'Medical Devices'), ('pharmacy', 'Pharmacy'), ('both', 'Both')], max_length=20)),
                ('license_image', models.ImageField(upload_to='store/licenses/')),
                ('license_expiry_date', models.DateField()),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store/logos/')),
                ('store_banner', models.ImageField(blank=True, null=True, upload_to='store/banners/')),
                ('description', models.TextField(blank=True, null=True)),
                ('devices', models.ManyToManyField(blank=True, to='inventory.medicaldevice')),
                ('medicines', models.ManyToManyField(blank=True, to='inventory.medicine')),
            ],
        ),
    ]
