# Generated by Django 5.2.3 on 2025-06-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstore',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalstore',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
