# Generated by Django 5.2.3 on 2025-06-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_stores', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalstore',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='medicalstore',
            name='medicines',
        ),
        migrations.AddField(
            model_name='medicalstore',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalstore',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
