# Generated by Django 5.2.3 on 2025-06-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_stores', '0003_remove_medicalstore_devices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstore',
            name='store_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
