# Generated by Django 5.2.3 on 2025-06-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_stores', '0002_medicalstore_latitude_medicalstore_longitude'),
        ('medical_stores', '0004_medicalstore_store_address'),
    ]

    operations = [
    ]
