# Generated by Django 5.2.3 on 2025-06-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_stores', '0005_merge_20250625_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstore',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalstore',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
