# Generated by Django 5.2.3 on 2025-06-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_stores', '0006_medicalstore_end_time_medicalstore_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstore',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalstore',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/licenses/'),
        ),
    ]
