# Generated by Django 5.2.3 on 2025-06-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_stores', '0007_alter_medicalstore_license_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstore',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
