# Generated by Django 5.2.3 on 2025-06-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('model_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('generic_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('chemical_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('atc_code', models.CharField(max_length=20)),
                ('cas_number', models.CharField(max_length=20)),
                ('alternative_medicines', models.ManyToManyField(blank=True, to='inventory.medicine')),
            ],
        ),
    ]
