# Generated by Django 5.2.3 on 2025-06-25 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('medical_stores', '0004_medicalstore_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldevice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicaldevice/images/'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_stores.medicalstore'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine/images/'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_stores.medicalstore'),
        ),
    ]
