# Generated by Django 5.2.3 on 2025-06-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldevice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicaldevice/images/'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine/images/'),
        ),
    ]
