# Generated by Django 5.2.3 on 2025-06-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicaldevice_image_medicaldevice_price_and_more'),
        ('inventory', '0002_medicaldevice_image_medicine_image'),
    ]

    operations = [
    ]
