# Generated by Django 5.2.3 on 2025-07-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_merge_20250625_2007'),
        ('medical_stores', '0008_medicalstore_phone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['brand_name'], name='inventory_m_brand_n_82f012_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['generic_name'], name='inventory_m_generic_acb93c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['chemical_name'], name='inventory_m_chemica_694422_idx'),
        ),
    ]
