# Generated by Django 5.2.3 on 2025-07-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_medicine_inventory_m_brand_n_82f012_idx_and_more'),
        ('medical_stores', '0008_medicalstore_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['is_deleted'], name='inventory_m_is_dele_6106aa_idx'),
        ),
    ]
