# Generated by Django 5.2.3 on 2025-06-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('on_process', 'On_Process'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], max_length=20),
        ),
    ]
