# Generated by Django 5.2.3 on 2025-07-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_shippingconfig_taxconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingConfig',
        ),
        migrations.DeleteModel(
            name='TaxConfig',
        ),
        migrations.AddField(
            model_name='order',
            name='total_with_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
