# Generated by Django 5.2.3 on 2025-07-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delete_shippingconfig_delete_taxconfig_and_more'),
        ('users', '0016_delivery_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.delivery'),
        ),
    ]
